/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Gets or Sets ActorType
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ActorType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ActorType
        {
            
            /// <summary>
            /// Enum UserEnum for user
            /// </summary>
            [EnumMember(Value = "user")]
            UserEnum = 1,
            
            /// <summary>
            /// Enum ContactEnum for contact
            /// </summary>
            [EnumMember(Value = "contact")]
            ContactEnum = 2,
            
            /// <summary>
            /// Enum PartnerEnum for partner
            /// </summary>
            [EnumMember(Value = "partner")]
            PartnerEnum = 3,
            
            /// <summary>
            /// Enum IntegrationEnum for integration
            /// </summary>
            [EnumMember(Value = "integration")]
            IntegrationEnum = 4
        }
}
