/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Type of billable item
        /// </summary>
        /// <value>Type of billable item</value>
        [TypeConverter(typeof(CustomEnumConverter<BillableItemTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BillableItemTypeEnum
        {
            
            /// <summary>
            /// Enum LaborEnum for labor
            /// </summary>
            [EnumMember(Value = "labor")]
            LaborEnum = 1,
            
            /// <summary>
            /// Enum MaterialEnum for material
            /// </summary>
            [EnumMember(Value = "material")]
            MaterialEnum = 2,
            
            /// <summary>
            /// Enum EquipmentEnum for equipment
            /// </summary>
            [EnumMember(Value = "equipment")]
            EquipmentEnum = 3,
            
            /// <summary>
            /// Enum UtilityEnum for utility
            /// </summary>
            [EnumMember(Value = "utility")]
            UtilityEnum = 4,
            
            /// <summary>
            /// Enum ServiceEnum for service
            /// </summary>
            [EnumMember(Value = "service")]
            ServiceEnum = 5,
            
            /// <summary>
            /// Enum OtherEnum for other
            /// </summary>
            [EnumMember(Value = "other")]
            OtherEnum = 6
        }
}
