/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Status of the charge
        /// </summary>
        /// <value>Status of the charge</value>
        [TypeConverter(typeof(CustomEnumConverter<ChargeStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ChargeStatus
        {
            
            /// <summary>
            /// Enum OpenEnum for open
            /// </summary>
            [EnumMember(Value = "open")]
            OpenEnum = 1,
            
            /// <summary>
            /// Enum VerifiedEnum for verified
            /// </summary>
            [EnumMember(Value = "verified")]
            VerifiedEnum = 2,
            
            /// <summary>
            /// Enum SyncInProgressEnum for sync_in_progress
            /// </summary>
            [EnumMember(Value = "sync_in_progress")]
            SyncInProgressEnum = 3,
            
            /// <summary>
            /// Enum SubmittedToAccountingEnum for submitted_to_accounting
            /// </summary>
            [EnumMember(Value = "submitted_to_accounting")]
            SubmittedToAccountingEnum = 4,
            
            /// <summary>
            /// Enum AccountingProcessingEnum for accounting_processing
            /// </summary>
            [EnumMember(Value = "accounting_processing")]
            AccountingProcessingEnum = 5,
            
            /// <summary>
            /// Enum AccountingErrorEnum for accounting_error
            /// </summary>
            [EnumMember(Value = "accounting_error")]
            AccountingErrorEnum = 6,
            
            /// <summary>
            /// Enum SettledEnum for settled
            /// </summary>
            [EnumMember(Value = "settled")]
            SettledEnum = 7
        }
}
