/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PauseHistoryRecord : IEquatable<PauseHistoryRecord>
    {
        /// <summary>
        /// Gets or Sets UpdatedByActor
        /// </summary>
        [Required]
        [DataMember(Name="updatedByActor", EmitDefaultValue=false)]
        public Actor UpdatedByActor { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [Required]
        [DataMember(Name="timestamp", EmitDefaultValue=true)]
        public DateTimeOffset Timestamp { get; set; }


        /// <summary>
        /// Action performed
        /// </summary>
        /// <value>Action performed</value>
        [TypeConverter(typeof(CustomEnumConverter<ActionEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ActionEnum
        {
            
            /// <summary>
            /// Enum PauseEnum for pause
            /// </summary>
            [EnumMember(Value = "pause")]
            PauseEnum = 1,
            
            /// <summary>
            /// Enum ActivateEnum for activate
            /// </summary>
            [EnumMember(Value = "activate")]
            ActivateEnum = 2
        }

        /// <summary>
        /// Action performed
        /// </summary>
        /// <value>Action performed</value>
        [Required]
        [DataMember(Name="action", EmitDefaultValue=true)]
        public ActionEnum Action { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PauseHistoryRecord {\n");
            sb.Append("  UpdatedByActor: ").Append(UpdatedByActor).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PauseHistoryRecord)obj);
        }

        /// <summary>
        /// Returns true if PauseHistoryRecord instances are equal
        /// </summary>
        /// <param name="other">Instance of PauseHistoryRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PauseHistoryRecord other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UpdatedByActor == other.UpdatedByActor ||
                    UpdatedByActor != null &&
                    UpdatedByActor.Equals(other.UpdatedByActor)
                ) && 
                (
                    Timestamp == other.Timestamp ||
                    
                    Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    Action == other.Action ||
                    
                    Action.Equals(other.Action)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (UpdatedByActor != null)
                    hashCode = hashCode * 59 + UpdatedByActor.GetHashCode();
                    
                    hashCode = hashCode * 59 + Timestamp.GetHashCode();
                    
                    hashCode = hashCode * 59 + Action.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PauseHistoryRecord left, PauseHistoryRecord right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PauseHistoryRecord left, PauseHistoryRecord right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
