/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Role of contact
        /// </summary>
        /// <value>Role of contact</value>
        [TypeConverter(typeof(CustomEnumConverter<RolesEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RolesEnum
        {
            
            /// <summary>
            /// Enum AdminEnum for admin
            /// </summary>
            [EnumMember(Value = "admin")]
            AdminEnum = 1,
            
            /// <summary>
            /// Enum EmergencyEnum for emergency
            /// </summary>
            [EnumMember(Value = "emergency")]
            EmergencyEnum = 2
        }
}
