/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Gets or Sets UserRole
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<UserRole>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UserRole
        {
            
            /// <summary>
            /// Enum AdminEnum for admin
            /// </summary>
            [EnumMember(Value = "admin")]
            AdminEnum = 1,
            
            /// <summary>
            /// Enum ManagerEnum for manager
            /// </summary>
            [EnumMember(Value = "manager")]
            ManagerEnum = 2,
            
            /// <summary>
            /// Enum TeamMemberEnum for team_member
            /// </summary>
            [EnumMember(Value = "team_member")]
            TeamMemberEnum = 3
        }
}
