/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Gets or Sets WorkOrderPriorityEnum
        /// </summary>
        
        public enum WorkOrderPriorityEnum
        {
            
            /// <summary>
            /// Enum _10Enum for 10
            /// </summary>
            
            _10Enum = 10,
            
            /// <summary>
            /// Enum _20Enum for 20
            /// </summary>
            
            _20Enum = 20,
            
            /// <summary>
            /// Enum _30Enum for 30
            /// </summary>
            
            _30Enum = 30
        }
}
