/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WorkOrdersBulkPutRequest : IEquatable<WorkOrdersBulkPutRequest>
    {
        /// <summary>
        /// Gets or Sets WorkOrderIds
        /// </summary>
        [Required]
        [DataMember(Name="workOrderIds", EmitDefaultValue=false)]
        public List<string> WorkOrderIds { get; set; }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [Required]
        [DataMember(Name="input", EmitDefaultValue=false)]
        public WorkOrderUpdateInput Input { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkOrdersBulkPutRequest {\n");
            sb.Append("  WorkOrderIds: ").Append(WorkOrderIds).Append("\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WorkOrdersBulkPutRequest)obj);
        }

        /// <summary>
        /// Returns true if WorkOrdersBulkPutRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of WorkOrdersBulkPutRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkOrdersBulkPutRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    WorkOrderIds == other.WorkOrderIds ||
                    WorkOrderIds != null &&
                    other.WorkOrderIds != null &&
                    WorkOrderIds.SequenceEqual(other.WorkOrderIds)
                ) && 
                (
                    Input == other.Input ||
                    Input != null &&
                    Input.Equals(other.Input)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (WorkOrderIds != null)
                    hashCode = hashCode * 59 + WorkOrderIds.GetHashCode();
                    if (Input != null)
                    hashCode = hashCode * 59 + Input.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WorkOrdersBulkPutRequest left, WorkOrdersBulkPutRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WorkOrdersBulkPutRequest left, WorkOrdersBulkPutRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
