/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InspectionEdit : IEquatable<InspectionEdit>
    {
        /// <summary>
        /// Gets or Sets EditedByActor
        /// </summary>
        [Required]
        [DataMember(Name="editedByActor", EmitDefaultValue=false)]
        public Actor EditedByActor { get; set; }

        /// <summary>
        /// Gets or Sets EditedAt
        /// </summary>
        [Required]
        [DataMember(Name="editedAt", EmitDefaultValue=true)]
        public DateTimeOffset EditedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InspectionEdit {\n");
            sb.Append("  EditedByActor: ").Append(EditedByActor).Append("\n");
            sb.Append("  EditedAt: ").Append(EditedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InspectionEdit)obj);
        }

        /// <summary>
        /// Returns true if InspectionEdit instances are equal
        /// </summary>
        /// <param name="other">Instance of InspectionEdit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InspectionEdit other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EditedByActor == other.EditedByActor ||
                    EditedByActor != null &&
                    EditedByActor.Equals(other.EditedByActor)
                ) && 
                (
                    EditedAt == other.EditedAt ||
                    
                    EditedAt.Equals(other.EditedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EditedByActor != null)
                    hashCode = hashCode * 59 + EditedByActor.GetHashCode();
                    
                    hashCode = hashCode * 59 + EditedAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InspectionEdit left, InspectionEdit right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InspectionEdit left, InspectionEdit right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
