/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
        /// <summary>
        /// Type of markup unit
        /// </summary>
        /// <value>Type of markup unit</value>
        [TypeConverter(typeof(CustomEnumConverter<MarkupUnitEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MarkupUnitEnum
        {
            
            /// <summary>
            /// Enum FixPriceEnum for fix_price
            /// </summary>
            [EnumMember(Value = "fix_price")]
            FixPriceEnum = 1,
            
            /// <summary>
            /// Enum PercentEnum for percent
            /// </summary>
            [EnumMember(Value = "percent")]
            PercentEnum = 2
        }
}
