/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
    /// <summary>
    /// filter users by role
    /// </summary>
    [DataContract]
    public partial class UserRoleFilter : IEquatable<UserRoleFilter>
    {
        /// <summary>
        /// Gets or Sets Eq
        /// </summary>
        [DataMember(Name="eq", EmitDefaultValue=true)]
        public UserRole? Eq { get; set; }

        /// <summary>
        /// Gets or Sets Neq
        /// </summary>
        [DataMember(Name="neq", EmitDefaultValue=true)]
        public UserRole? Neq { get; set; }

        /// <summary>
        /// Gets or Sets In
        /// </summary>
        [DataMember(Name="in", EmitDefaultValue=false)]
        public List<UserRole> In { get; set; }

        /// <summary>
        /// Gets or Sets Nin
        /// </summary>
        [DataMember(Name="nin", EmitDefaultValue=false)]
        public List<UserRole> Nin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserRoleFilter {\n");
            sb.Append("  Eq: ").Append(Eq).Append("\n");
            sb.Append("  Neq: ").Append(Neq).Append("\n");
            sb.Append("  In: ").Append(In).Append("\n");
            sb.Append("  Nin: ").Append(Nin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserRoleFilter)obj);
        }

        /// <summary>
        /// Returns true if UserRoleFilter instances are equal
        /// </summary>
        /// <param name="other">Instance of UserRoleFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserRoleFilter other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Eq == other.Eq ||
                    
                    Eq.Equals(other.Eq)
                ) && 
                (
                    Neq == other.Neq ||
                    
                    Neq.Equals(other.Neq)
                ) && 
                (
                    In == other.In ||
                    In != null &&
                    other.In != null &&
                    In.SequenceEqual(other.In)
                ) && 
                (
                    Nin == other.Nin ||
                    Nin != null &&
                    other.Nin != null &&
                    Nin.SequenceEqual(other.Nin)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Eq.GetHashCode();
                    
                    hashCode = hashCode * 59 + Neq.GetHashCode();
                    if (In != null)
                    hashCode = hashCode * 59 + In.GetHashCode();
                    if (Nin != null)
                    hashCode = hashCode * 59 + Nin.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UserRoleFilter left, UserRoleFilter right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserRoleFilter left, UserRoleFilter right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
