/*
 * Visitt Dashboard API
 *
 * API for Visitt calls and analytics in Azrieli complexes
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: benayan@one1.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VisitService.Converters;

namespace VisitService.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WorkOrderUpdateInput : IEquatable<WorkOrderUpdateInput>
    {
        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [MaxLength(5000)]
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public WorkOrderStatus? Status { get; set; }

        /// <summary>
        /// Gets or Sets StatusText
        /// </summary>
        [DataMember(Name="statusText", EmitDefaultValue=false)]
        public string? StatusText { get; set; }

        /// <summary>
        /// Gets or Sets AssignedUserIds
        /// </summary>
        [DataMember(Name="assignedUserIds", EmitDefaultValue=false)]
        public List<string> AssignedUserIds { get; set; }

        /// <summary>
        /// Gets or Sets BuildingId
        /// </summary>
        [DataMember(Name="buildingId", EmitDefaultValue=false)]
        public string? BuildingId { get; set; }

        /// <summary>
        /// Gets or Sets SiteId
        /// </summary>
        [DataMember(Name="siteId", EmitDefaultValue=false)]
        public string? SiteId { get; set; }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [DataMember(Name="categoryId", EmitDefaultValue=false)]
        public string? CategoryId { get; set; }

        /// <summary>
        /// Gets or Sets SubCategoryId
        /// </summary>
        [DataMember(Name="subCategoryId", EmitDefaultValue=false)]
        public string? SubCategoryId { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name="priority", EmitDefaultValue=true)]
        public WorkOrderPriorityEnum? Priority { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkOrderUpdateInput {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusText: ").Append(StatusText).Append("\n");
            sb.Append("  AssignedUserIds: ").Append(AssignedUserIds).Append("\n");
            sb.Append("  BuildingId: ").Append(BuildingId).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  SubCategoryId: ").Append(SubCategoryId).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WorkOrderUpdateInput)obj);
        }

        /// <summary>
        /// Returns true if WorkOrderUpdateInput instances are equal
        /// </summary>
        /// <param name="other">Instance of WorkOrderUpdateInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkOrderUpdateInput other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    StatusText == other.StatusText ||
                    StatusText != null &&
                    StatusText.Equals(other.StatusText)
                ) && 
                (
                    AssignedUserIds == other.AssignedUserIds ||
                    AssignedUserIds != null &&
                    other.AssignedUserIds != null &&
                    AssignedUserIds.SequenceEqual(other.AssignedUserIds)
                ) && 
                (
                    BuildingId == other.BuildingId ||
                    BuildingId != null &&
                    BuildingId.Equals(other.BuildingId)
                ) && 
                (
                    SiteId == other.SiteId ||
                    SiteId != null &&
                    SiteId.Equals(other.SiteId)
                ) && 
                (
                    CategoryId == other.CategoryId ||
                    CategoryId != null &&
                    CategoryId.Equals(other.CategoryId)
                ) && 
                (
                    SubCategoryId == other.SubCategoryId ||
                    SubCategoryId != null &&
                    SubCategoryId.Equals(other.SubCategoryId)
                ) && 
                (
                    Priority == other.Priority ||
                    
                    Priority.Equals(other.Priority)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (StatusText != null)
                    hashCode = hashCode * 59 + StatusText.GetHashCode();
                    if (AssignedUserIds != null)
                    hashCode = hashCode * 59 + AssignedUserIds.GetHashCode();
                    if (BuildingId != null)
                    hashCode = hashCode * 59 + BuildingId.GetHashCode();
                    if (SiteId != null)
                    hashCode = hashCode * 59 + SiteId.GetHashCode();
                    if (CategoryId != null)
                    hashCode = hashCode * 59 + CategoryId.GetHashCode();
                    if (SubCategoryId != null)
                    hashCode = hashCode * 59 + SubCategoryId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WorkOrderUpdateInput left, WorkOrderUpdateInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WorkOrderUpdateInput left, WorkOrderUpdateInput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
